/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MoyenneRouteImport } from './routes/moyenne'
import { Route as ResultatsRouteImport } from './routes/resultats'
import { Route as ApiWebProxyRouteImport } from './routes/api/web-proxy'
import { Route as ApiPublicCloudinaryConfigRouteImport } from './routes/api/public/cloudinary/config'
import { Route as ApiPublicCloudinaryDestroyRouteImport } from './routes/api/public/cloudinary/destroy'
import { Route as ApiPublicCloudinarySignRouteImport } from './routes/api/public/cloudinary/sign'
import { Route as ApiPublicFcmRegisterRouteImport } from './routes/api/public/fcm/register'
import { Route as ApiPublicPushSendRouteImport } from './routes/api/public/push/send'
import { Route as ApiPublicPushVapidKeyRouteImport } from './routes/api/public/push/vapid-key'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoyenneRoute = MoyenneRouteImport.update({
  id: '/moyenne',
  path: '/moyenne',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultatsRoute = ResultatsRouteImport.update({
  id: '/resultats',
  path: '/resultats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebProxyRoute = ApiWebProxyRouteImport.update({
  id: '/api/web-proxy',
  path: '/api/web-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCloudinaryConfigRoute =
  ApiPublicCloudinaryConfigRouteImport.update({
    id: '/api/public/cloudinary/config',
    path: '/api/public/cloudinary/config',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCloudinaryDestroyRoute =
  ApiPublicCloudinaryDestroyRouteImport.update({
    id: '/api/public/cloudinary/destroy',
    path: '/api/public/cloudinary/destroy',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCloudinarySignRoute = ApiPublicCloudinarySignRouteImport.update({
  id: '/api/public/cloudinary/sign',
  path: '/api/public/cloudinary/sign',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFcmRegisterRoute = ApiPublicFcmRegisterRouteImport.update({
  id: '/api/public/fcm/register',
  path: '/api/public/fcm/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushSendRoute = ApiPublicPushSendRouteImport.update({
  id: '/api/public/push/send',
  path: '/api/public/push/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPushVapidKeyRoute = ApiPublicPushVapidKeyRouteImport.update({
  id: '/api/public/push/vapid-key',
  path: '/api/public/push/vapid-key',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/moyenne': typeof MoyenneRoute
  '/resultats': typeof ResultatsRoute
  '/api/web-proxy': typeof ApiWebProxyRoute
  '/api/public/cloudinary/config': typeof ApiPublicCloudinaryConfigRoute
  '/api/public/cloudinary/destroy': typeof ApiPublicCloudinaryDestroyRoute
  '/api/public/cloudinary/sign': typeof ApiPublicCloudinarySignRoute
  '/api/public/fcm/register': typeof ApiPublicFcmRegisterRoute
  '/api/public/push/send': typeof ApiPublicPushSendRoute
  '/api/public/push/vapid-key': typeof ApiPublicPushVapidKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/moyenne': typeof MoyenneRoute
  '/resultats': typeof ResultatsRoute
  '/api/web-proxy': typeof ApiWebProxyRoute
  '/api/public/cloudinary/config': typeof ApiPublicCloudinaryConfigRoute
  '/api/public/cloudinary/destroy': typeof ApiPublicCloudinaryDestroyRoute
  '/api/public/cloudinary/sign': typeof ApiPublicCloudinarySignRoute
  '/api/public/fcm/register': typeof ApiPublicFcmRegisterRoute
  '/api/public/push/send': typeof ApiPublicPushSendRoute
  '/api/public/push/vapid-key': typeof ApiPublicPushVapidKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/moyenne': typeof MoyenneRoute
  '/resultats': typeof ResultatsRoute
  '/api/web-proxy': typeof ApiWebProxyRoute
  '/api/public/cloudinary/config': typeof ApiPublicCloudinaryConfigRoute
  '/api/public/cloudinary/destroy': typeof ApiPublicCloudinaryDestroyRoute
  '/api/public/cloudinary/sign': typeof ApiPublicCloudinarySignRoute
  '/api/public/fcm/register': typeof ApiPublicFcmRegisterRoute
  '/api/public/push/send': typeof ApiPublicPushSendRoute
  '/api/public/push/vapid-key': typeof ApiPublicPushVapidKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/moyenne'
    | '/resultats'
    | '/api/web-proxy'
    | '/api/public/cloudinary/config'
    | '/api/public/cloudinary/destroy'
    | '/api/public/cloudinary/sign'
    | '/api/public/fcm/register'
    | '/api/public/push/send'
    | '/api/public/push/vapid-key'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/moyenne'
    | '/resultats'
    | '/api/web-proxy'
    | '/api/public/cloudinary/config'
    | '/api/public/cloudinary/destroy'
    | '/api/public/cloudinary/sign'
    | '/api/public/fcm/register'
    | '/api/public/push/send'
    | '/api/public/push/vapid-key'
  id:
    | '__root__'
    | '/'
    | '/moyenne'
    | '/resultats'
    | '/api/web-proxy'
    | '/api/public/cloudinary/config'
    | '/api/public/cloudinary/destroy'
    | '/api/public/cloudinary/sign'
    | '/api/public/fcm/register'
    | '/api/public/push/send'
    | '/api/public/push/vapid-key'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MoyenneRoute: typeof MoyenneRoute
  ResultatsRoute: typeof ResultatsRoute
  ApiWebProxyRoute: typeof ApiWebProxyRoute
  ApiPublicCloudinaryConfigRoute: typeof ApiPublicCloudinaryConfigRoute
  ApiPublicCloudinaryDestroyRoute: typeof ApiPublicCloudinaryDestroyRoute
  ApiPublicCloudinarySignRoute: typeof ApiPublicCloudinarySignRoute
  ApiPublicFcmRegisterRoute: typeof ApiPublicFcmRegisterRoute
  ApiPublicPushSendRoute: typeof ApiPublicPushSendRoute
  ApiPublicPushVapidKeyRoute: typeof ApiPublicPushVapidKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moyenne': {
      id: '/moyenne'
      path: '/moyenne'
      fullPath: '/moyenne'
      preLoaderRoute: typeof MoyenneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultats': {
      id: '/resultats'
      path: '/resultats'
      fullPath: '/resultats'
      preLoaderRoute: typeof ResultatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/web-proxy': {
      id: '/api/web-proxy'
      path: '/api/web-proxy'
      fullPath: '/api/web-proxy'
      preLoaderRoute: typeof ApiWebProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cloudinary/config': {
      id: '/api/public/cloudinary/config'
      path: '/api/public/cloudinary/config'
      fullPath: '/api/public/cloudinary/config'
      preLoaderRoute: typeof ApiPublicCloudinaryConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cloudinary/destroy': {
      id: '/api/public/cloudinary/destroy'
      path: '/api/public/cloudinary/destroy'
      fullPath: '/api/public/cloudinary/destroy'
      preLoaderRoute: typeof ApiPublicCloudinaryDestroyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cloudinary/sign': {
      id: '/api/public/cloudinary/sign'
      path: '/api/public/cloudinary/sign'
      fullPath: '/api/public/cloudinary/sign'
      preLoaderRoute: typeof ApiPublicCloudinarySignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fcm/register': {
      id: '/api/public/fcm/register'
      path: '/api/public/fcm/register'
      fullPath: '/api/public/fcm/register'
      preLoaderRoute: typeof ApiPublicFcmRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push/send': {
      id: '/api/public/push/send'
      path: '/api/public/push/send'
      fullPath: '/api/public/push/send'
      preLoaderRoute: typeof ApiPublicPushSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/push/vapid-key': {
      id: '/api/public/push/vapid-key'
      path: '/api/public/push/vapid-key'
      fullPath: '/api/public/push/vapid-key'
      preLoaderRoute: typeof ApiPublicPushVapidKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MoyenneRoute: MoyenneRoute,
  ResultatsRoute: ResultatsRoute,
  ApiWebProxyRoute: ApiWebProxyRoute,
  ApiPublicCloudinaryConfigRoute: ApiPublicCloudinaryConfigRoute,
  ApiPublicCloudinaryDestroyRoute: ApiPublicCloudinaryDestroyRoute,
  ApiPublicCloudinarySignRoute: ApiPublicCloudinarySignRoute,
  ApiPublicFcmRegisterRoute: ApiPublicFcmRegisterRoute,
  ApiPublicPushSendRoute: ApiPublicPushSendRoute,
  ApiPublicPushVapidKeyRoute: ApiPublicPushVapidKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
